---
- hosts: all
  sudo: yes
  tasks:
  - name: install nginx on the node
    apt: 
      pkg: nginx
      state: installed
  - name: start nginx server
    service: 
      name: nginx
      state: started